export const codeInvitationConstants= {
    GET_CODEINVITATION_REQUEST: 'GET_CODEINVITATION_REQUEST',
    GET_CODEINVITATION_SUCCESS: 'GET_CODEINVITATION_SUCCESS',
    GET_CODEINVITATION_FAIL: 'GET_CODEINVITATION_FAIL',
}